#!/bin/bash
#SBATCH --job-name=JOB_ID_NAME
#SBATCH --nodes=1-1
## SBATCH --ntasks=8
##SBATCH --ntasks=27
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00
#SBATCH --output=./output/job%2t-%s.out

echo "Hello! I'm job with ID ${SLURM_JOBID}."
echo "I'm running on compute node(s) ${SLURM_JOB_NODELIST}."

module load OpenMPI

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

cd ./example_inputs/testing3d

srun ../../fdtd ./param_3d.txt